### ISSUE TITLE
Hang after a while for BSC operation, happens for ETH flow as well

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/ethhmy-bridge.frontend#84] opened 2021-03-17 06:06 UTC
<img width="1253" alt="Screen Shot 2021-03-16 at 11 03 38 PM" src="https://user-images.githubusercontent.com/13854340/111422427-edad0180-86ab-11eb-9633-5e325ddb1811.png">

**Comment by gupadhyaya** [comment] 2021-03-17 06:07
<img width="1218" alt="Screen Shot 2021-03-16 at 11 06 16 PM" src="https://user-images.githubusercontent.com/13854340/111422657-3fee2280-86ac-11eb-9033-4c2def17fc7c.png">

I think this looks like some UI issue while loading bridge wallet contents?

**Comment by gupadhyaya** [comment] 2021-03-17 06:11
<img width="1204" alt="Screen Shot 2021-03-16 at 11 11 02 PM" src="https://user-images.githubusercontent.com/13854340/111423029-e63a2800-86ac-11eb-904c-b8b8deb8f074.png">

here you can see that, harmony transaction succeeded, however the bridge wallet does not show the balance.

**Comment by potvik** [comment] 2021-03-18 01:22
can't reproduce on my side

**Comment by potvik** [comment] 2021-03-19 23:40
Should be fixed

**Closed by potvik** 2021-03-19 23:40 UTC
